### ISSUE TITLE
Broken link on the LangChain Decoded: Part 2 - Embeddings blog post

### ISSUE THREAD

**Issue by erikfrerejean** [alphasecio/langchain-decoded#2]
This seems to be the best way to report this, I'm following along with your LangChain Decoded series _(thanks for those! 👌)_, however in part two the link to open the notebook in google colab is broken, at it points to https://colab.research.google.com/github/alphasecio/langchain-decoded/blob/main/langchain_decoded_2_embeddings.ipynb rather then https://github.com/alphasecio/langchain-decoded/blob/main/notebooks/langchain_decoded_2_embeddings.ipynb.

**Comment by alphasecio** [comment]
Thank you for taking the time to report this - I moved the notebook under the `notebooks` folder and missed updating this link. Fixed now.
